package com.whcst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-28T14:56:44.740+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://www.whcst.com/",name = "SiteWebserviceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SiteWebserviceSoap {

    /**
     * 卡押金相关信息
     */
    @WebResult(name = "CardDepositInfoResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CardDepositInfo", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardDepositInfo")
    @WebMethod(operationName = "CardDepositInfo", action = "http://www.whcst.com/CardDepositInfo")
    @ResponseWrapper(localName = "CardDepositInfoResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardDepositInfoResponse")
    public java.lang.String cardDepositInfo(
        @WebParam(name = "code", targetNamespace = "http://www.whcst.com/")
        java.lang.String code,
        @WebParam(name = "cardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String cardno
    );

    /**
     * 武汉通账户卡片绑定
     */
    @WebResult(name = "CardBindResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CardBind", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardBind")
    @WebMethod(operationName = "CardBind", action = "http://www.whcst.com/CardBind")
    @ResponseWrapper(localName = "CardBindResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardBindResponse")
    public java.lang.String cardBind(
        @WebParam(name = "mastercardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String mastercardno,
        @WebParam(name = "childcardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String childcardno,
        @WebParam(name = "passwd", targetNamespace = "http://www.whcst.com/")
        java.lang.String passwd,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 武汉通账户密码重置
     */
    @WebResult(name = "ResetPasswdResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "ResetPasswd", targetNamespace = "http://www.whcst.com/", className = "com.whcst.ResetPasswd")
    @WebMethod(operationName = "ResetPasswd", action = "http://www.whcst.com/ResetPasswd")
    @ResponseWrapper(localName = "ResetPasswdResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.ResetPasswdResponse")
    public java.lang.String resetPasswd(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "newpasswd", targetNamespace = "http://www.whcst.com/")
        java.lang.String newpasswd,
        @WebParam(name = "passwdtype", targetNamespace = "http://www.whcst.com/")
        java.lang.String passwdtype,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 卡片十笔交易明细
     */
    @WebResult(name = "CardTradeResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CardTrade", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardTrade")
    @WebMethod(operationName = "CardTrade", action = "http://www.whcst.com/CardTrade")
    @ResponseWrapper(localName = "CardTradeResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardTradeResponse")
    public java.lang.String cardTrade(
        @WebParam(name = "cardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String cardno,
        @WebParam(name = "code", targetNamespace = "http://www.whcst.com/")
        java.lang.String code
    );

    /**
     * 发送短信验证码
     */
    @WebResult(name = "SendCodeResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "SendCode", targetNamespace = "http://www.whcst.com/", className = "com.whcst.SendCode")
    @WebMethod(operationName = "SendCode", action = "http://www.whcst.com/SendCode")
    @ResponseWrapper(localName = "SendCodeResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.SendCodeResponse")
    public java.lang.String sendCode(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "codetype", targetNamespace = "http://www.whcst.com/")
        java.lang.String codetype
    );

    /**
     * 武汉通账户登录
     */
    @WebResult(name = "AccLoginResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "AccLogin", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccLogin")
    @WebMethod(operationName = "AccLogin", action = "http://www.whcst.com/AccLogin")
    @ResponseWrapper(localName = "AccLoginResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccLoginResponse")
    public java.lang.String accLogin(
        @WebParam(name = "accountno", targetNamespace = "http://www.whcst.com/")
        java.lang.String accountno,
        @WebParam(name = "passwd", targetNamespace = "http://www.whcst.com/")
        java.lang.String passwd
    );

    /**
     * 武汉通账户开户
     */
    @WebResult(name = "AccOpenResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "AccOpen", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccOpen")
    @WebMethod(operationName = "AccOpen", action = "http://www.whcst.com/AccOpen")
    @ResponseWrapper(localName = "AccOpenResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccOpenResponse")
    public java.lang.String accOpen(
        @WebParam(name = "cardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String cardno,
        @WebParam(name = "txnpasswd", targetNamespace = "http://www.whcst.com/")
        java.lang.String txnpasswd,
        @WebParam(name = "qrypasswd", targetNamespace = "http://www.whcst.com/")
        java.lang.String qrypasswd,
        @WebParam(name = "name", targetNamespace = "http://www.whcst.com/")
        java.lang.String name,
        @WebParam(name = "idtype", targetNamespace = "http://www.whcst.com/")
        java.lang.String idtype,
        @WebParam(name = "idcardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String idcardno,
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 伽乾益App快捷登录
     */
    @WebResult(name = "AppLoginUrlResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "AppLoginUrl", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AppLoginUrl")
    @WebMethod(operationName = "AppLoginUrl", action = "http://www.whcst.com/AppLoginUrl")
    @ResponseWrapper(localName = "AppLoginUrlResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AppLoginUrlResponse")
    public java.lang.String appLoginUrl(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "remoteip", targetNamespace = "http://www.whcst.com/")
        java.lang.String remoteip,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 判断是否存在交易密码
     */
    @WebResult(name = "CheckTxnPasswdResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CheckTxnPasswd", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CheckTxnPasswd")
    @WebMethod(operationName = "CheckTxnPasswd", action = "http://www.whcst.com/CheckTxnPasswd")
    @ResponseWrapper(localName = "CheckTxnPasswdResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CheckTxnPasswdResponse")
    public java.lang.String checkTxnPasswd(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone
    );

    /**
     * 武汉通账户交易明细
     */
    @WebResult(name = "AccTradeResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "AccTrade", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccTrade")
    @WebMethod(operationName = "AccTrade", action = "http://www.whcst.com/AccTrade")
    @ResponseWrapper(localName = "AccTradeResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccTradeResponse")
    public java.lang.String accTrade(
        @WebParam(name = "cardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String cardno,
        @WebParam(name = "code", targetNamespace = "http://www.whcst.com/")
        java.lang.String code
    );

    /**
     * 武汉通账户卡片解绑
     */
    @WebResult(name = "CardUnBindResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CardUnBind", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardUnBind")
    @WebMethod(operationName = "CardUnBind", action = "http://www.whcst.com/CardUnBind")
    @ResponseWrapper(localName = "CardUnBindResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardUnBindResponse")
    public java.lang.String cardUnBind(
        @WebParam(name = "mastercardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String mastercardno,
        @WebParam(name = "childcardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String childcardno,
        @WebParam(name = "passwd", targetNamespace = "http://www.whcst.com/")
        java.lang.String passwd,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 武汉通账户密码修改
     */
    @WebResult(name = "ManagePasswdResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "ManagePasswd", targetNamespace = "http://www.whcst.com/", className = "com.whcst.ManagePasswd")
    @WebMethod(operationName = "ManagePasswd", action = "http://www.whcst.com/ManagePasswd")
    @ResponseWrapper(localName = "ManagePasswdResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.ManagePasswdResponse")
    public java.lang.String managePasswd(
        @WebParam(name = "cardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String cardno,
        @WebParam(name = "oldpasswd", targetNamespace = "http://www.whcst.com/")
        java.lang.String oldpasswd,
        @WebParam(name = "newpasswd", targetNamespace = "http://www.whcst.com/")
        java.lang.String newpasswd,
        @WebParam(name = "passwdtype", targetNamespace = "http://www.whcst.com/")
        java.lang.String passwdtype,
        @WebParam(name = "idtype", targetNamespace = "http://www.whcst.com/")
        java.lang.String idtype,
        @WebParam(name = "idcardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String idcardno,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * 武汉通账户客户信息
     */
    @WebResult(name = "AccInfoResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "AccInfo", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccInfo")
    @WebMethod(operationName = "AccInfo", action = "http://www.whcst.com/AccInfo")
    @ResponseWrapper(localName = "AccInfoResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.AccInfoResponse")
    public java.lang.String accInfo(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "code", targetNamespace = "http://www.whcst.com/")
        java.lang.String code
    );

    /**
     * 武汉通账户卡片绑定查询
     */
    @WebResult(name = "CardBindSearchResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "CardBindSearch", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardBindSearch")
    @WebMethod(operationName = "CardBindSearch", action = "http://www.whcst.com/CardBindSearch")
    @ResponseWrapper(localName = "CardBindSearchResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.CardBindSearchResponse")
    public java.lang.String cardBindSearch(
        @WebParam(name = "mastercardno", targetNamespace = "http://www.whcst.com/")
        java.lang.String mastercardno,
        @WebParam(name = "code", targetNamespace = "http://www.whcst.com/")
        java.lang.String code
    );

    /**
     * 伽乾益Web快捷登录
     */
    @WebResult(name = "WebLoginUrlResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "WebLoginUrl", targetNamespace = "http://www.whcst.com/", className = "com.whcst.WebLoginUrl")
    @WebMethod(operationName = "WebLoginUrl", action = "http://www.whcst.com/WebLoginUrl")
    @ResponseWrapper(localName = "WebLoginUrlResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.WebLoginUrlResponse")
    public java.lang.String webLoginUrl(
        @WebParam(name = "phone", targetNamespace = "http://www.whcst.com/")
        java.lang.String phone,
        @WebParam(name = "remoteip", targetNamespace = "http://www.whcst.com/")
        java.lang.String remoteip,
        @WebParam(name = "unitid", targetNamespace = "http://www.whcst.com/")
        java.lang.String unitid
    );

    /**
     * DES解密
     */
    @WebResult(name = "DecodeResult", targetNamespace = "http://www.whcst.com/")
    @RequestWrapper(localName = "Decode", targetNamespace = "http://www.whcst.com/", className = "com.whcst.Decode")
    @WebMethod(operationName = "Decode", action = "http://www.whcst.com/Decode")
    @ResponseWrapper(localName = "DecodeResponse", targetNamespace = "http://www.whcst.com/", className = "com.whcst.DecodeResponse")
    public java.lang.String decode(
        @WebParam(name = "text", targetNamespace = "http://www.whcst.com/")
        java.lang.String text,
        @WebParam(name = "key", targetNamespace = "http://www.whcst.com/")
        java.lang.String key
    );
}
